services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontnet
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:8080"
        depends_on:
            - frontend 
        develop:
        networks:
            - frontnet


networks:
  frontnet:
    driver: bridge