services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
    networks:
      - frontnet
  nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:8080"
        depends_on:
            - frontend 
        develop:
        networks:
            - frontnet


networks:
  frontnet:
    driver: bridge